[build]
  command = "npm install"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/host"
  to = "/host.html"
  status = 200
